config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts, only: [:create, :index, :update, :new, :show, :upvote, :downvote] do
    resources :comments, only: [:create, :update, :new, :show, :destroy]
  end
  # Comments on a comment
  resources :comments do
    resources :comments, only: [:create]
  end

  resources :teams, only: [:index, :show]
  resources :follows, only: [:new, :create, :update, :show]
  resources :player_follows, only: [:new, :create, :update, :show]
  resources :people, only: [:index, :show]
  resources :games, only: [:index, :show]
  resources :standings, only: :index

  resources :users do
    get :follow
    get :unfollow
  end
  resources :posts do
    member do
  get "upvote", to: "posts#upvote"
  get "downvote", to: "posts#downvote"
    end
  end

  get "dashboard", to: "dashboards#dashboard", as: :dashboard
end

app/views/shared/_comment.html.erb
<%= simple_form_for([@post, @comment]) do |f| %>
  <%= f.input :text, label: false, placeholder: "Comment here.." %>
  <%= f.button :submit, "Submit", label: false, class: 'new-post-btn' %>
<% end %>

app/views/shared/_comment_form.html.erb
<%= simple_form_for([parent, comment], remote: remote) do |f| %>
  <%= f.input :text, label: false, placeholder: "Comment here.." %>
  <%= f.button :submit, "Submit", label: false, class: 'new-post-btn' %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- <style>
.site-footer {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
}
</style>


<footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2019 All Rights Reserved by
         <a href="#">Swish</a>.
            </p>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fab fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fab fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fas fa-basketball-ball"></i></i></a></li>
              <li><a class="linkedin" href="#"><i class="fab fa-linkedin-in"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
</footer> -->

app/views/shared/_form.html.erb
<div class="new-post">
  <div class="">
    <%= simple_form_for (@post) do |f| %>
      <h6>Topic Title</h6>
        <%= f.input :title, label: false %>
      <h6>Description</h6>
      <%= f.input :content, label: false, placeholder: "Talk about something.." %>
      <%= f.association :team, collection:  current_user.following_by_type('Team') %>
      <%= f.association :person, collection:  current_user.following_by_type('Person').map { |person| [ person.full_name, person.id,] } %>
      <label class="btn add-image-btn">
        <i class="fas fa-image"></i>
        <span style="display:none;">
          <%= f.input :photo, as: :file %>
          <%= f.input :photo_cache, :as => :hidden %>
        </span>
      </label>
      <%= image_tag(@post.photo.url ||'blankpng.png',  class: 'post_photo_preview', height: 100, width: 100) %>
      <%= f.input :user_generated, as: :hidden, value: true %>
      <%= f.button :submit, "Shoot!", label: false, class: 'new-post-btn' %>
    <% end %>
  </div>
</div>


<script>
  const postPhoto = document.querySelector('#post_photo');
  const photoPreview = document.querySelector('.post_photo_preview');

  postPhoto.addEventListener('change', event => {
    const reader = new FileReader();
    const file = event.currentTarget.files[0];
    reader.addEventListener('load', readerEvent => {
      image_base64 = readerEvent.target.result;
      photoPreview.setAttribute('src', image_base64);
    })
    reader.readAsDataURL(file);
  })
</script>

app/views/shared/_games_grid.html.erb
<% if user_signed_in? %>
  <div class="d-flex flex-row navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% today = Time.now %>
        <% lasterday = today - (86400 * 2) %>
        <% stoday = "#{today.year}#{format('%02i', today.month)}#{format('%02i', today.day)}" %>
        <% slasterday = "#{lasterday.year}#{format('%02i', lasterday.month)}#{format('%02i', lasterday.day)}" %>
        <% games.all.where(date: slasterday...stoday).each do |game| %>
          <div class="navbar-score-card">
            <%= "#{game.date[4..5]}-#{game.date[6..7]}" %>
            <table>
              <tr>
                <td class="bold"><%= link_to game.vTeam.abbrevation, team_path(Team.find(game.vTeam.id)) %></td>
                <td class="bold"><%= game.vTeamScore %></td>
              </tr>
              <tr>
                <td class="bold"><%= link_to game.hTeam.abbrevation, team_path(Team.find(game.vTeam.id)) %></td>
                <td class="bold"><%= game.hTeamScore %></td>
              </tr>
            </table>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="d-flex flex-row navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <div class="d-flex align-items-end">
        <%= cl_image_tag "https://res.cloudinary.com/dg6wajgky/image/upload/v1575541123/basketballlogoblank_js4fxo.png"%>
        <h3 class="logo-text">Swish</h3>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <button class="btn-nav">
          <%= link_to "Home", root_path, class: "nav-link" %>
          </button>
        </li>
        <li>
          <button class="btn-nav">
          <%= link_to "Forum", posts_path, class: "nav-link #{'active-nav-item' if params[:controller] == 'posts'}" %>
          </button>
        </li>
        <li>
          <button class="btn-nav">
          <%= link_to "Scores", games_path, class: "nav-link" %>
          </button>
        </li>
        <li>
          <button class="btn-nav">
         <%= link_to "Standings", standings_path, class: "nav-link" %>
          </button>
        </li>
        <li>
          <button class="btn-nav">
          <%= link_to "Teams", teams_path, class: "nav-link #{'active-nav-item' if params[:controller] == 'teams'}" %>
          </button>
        </li>
        <li>
          <button class="btn-nav">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </button>
        </li>
      </ul>
    </div>


  <div class="nav-item dropdown btn">
    <% if user_signed_in? %>
      <% if current_user.photo.file.nil? %>
        <%= cl_image_tag "default-profile-picture1_gxixjx", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
        <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <div class="btn-nav nav-link">
            <%= current_user.email %>
          </div>
          <%= link_to "Dashboard", dashboard_path, class: "dropdown-item btn-nav nav-link" %>
          <%= link_to "Update Teams", new_follow_path, class: "dropdown-item btn-nav nav-link" %>
          <%= link_to "Update Players", new_player_follow_path, class: "dropdown-item btn-nav nav-link" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item btn-nav nav-link" %>
        </div>
      <% end  %>
    </div>
  </div>
<% end %>