config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts, only: [:create, :index, :update, :new, :show, :upvote, :downvote] do
    resources :comments, only: [:create, :update, :new, :show, :destroy]
  end
  # Comments on a comment
  resources :comments do
    resources :comments, only: [:create]
  end

  resources :teams, only: [:index, :show]
  resources :follows, only: [:new, :create, :update, :show]
  resources :player_follows, only: [:new, :create, :update, :show]
  resources :people, only: [:index, :show]
  resources :games, only: [:index, :show]
  resources :standings, only: :index

  resources :users do
    get :follow
    get :unfollow
  end
  resources :posts do
    member do
  get "upvote", to: "posts#upvote"
  get "downvote", to: "posts#downvote"
    end
  end

  get "dashboard", to: "dashboards#dashboard", as: :dashboard
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :team, optional: true
  belongs_to :person, optional: true
  # belongs_to :people, source: "Person"
  has_many :comments, as: :commentable
  validates :title, presence: true
  mount_uploader :photo, PhotoUploader
  acts_as_votable

def upvote

  @post = Post.find(params[:id])
  if current_user.up_votes @post
    @post.unvote_up current_user
  else
    @post.upvote_by current_user
  end

  @post.create_activity :upvote, owner: current_user

end

  def person_id
    people_id
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :set_post, only: [:show]

  def index
    @post = Post.new
    @posts = policy_scope(Post).order(created_at: :desc)

    if user_signed_in?
      @myposts = current_user.posts.order(created_at: :desc)
      @professionals_posts = Post.where(team_id: current_user.following_by_type('Team').pluck(:id)).or(Post.where(people_id: current_user.following_by_type('Person').pluck(:id))).order(created_at: :desc)
    else
      @myposts = Post.all.order(created_at: :desc)
      @professionals_posts = Post.all
    end
  end

  def new
    @post = Post.new
    @post.title = params[:title] if params.include?(:title)
    @post.content = params[:content] if params.include?(:content)
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    @post.people_id = params[:post][:person_id]
    @post.user = current_user
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
    authorize @post
  end

  def show
    @post = Post.find(params[:id])
    authorize @post
    @comment = Comment.new
  end
  # upvote from user

  def upvote
    @post = Post.find(params[:id])
    authorize @post
    @post.upvote_from current_user
    respond_to do |format|
      format.html { redirect_to posts_path(@post) }
      format.js
    end
    # @post = policy_scope(Post).order(created_at: :desc)
  end
  # downvote from user

  def downvote
    @post = Post.find(params[:id])
    authorize @post
    @post.downvote_from current_user
    respond_to do |format|
      format.html { redirect_to posts_path(@post) }
      format.js
    end
    # @post = policy_scope(Post).order(created_at: :desc)
  end

  private

  def post_params
    params.require(:post).permit(:title, :category, :photo, :user_generated, :content, :team_id)
  end

  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end
end

app/views/posts/downvote.js.erb
function downvote(){

  const likePost = document.querySelector('.like_post');
  const unlikePost = document.querySelector('.unlike_post');
  const likeVoteCount = likePost.querySelector('.vote_count');
  const unlikeVoteCount = unlikePost.querySelector('.vote_count');

  likeVoteCount.innerText = "<%= @post.get_upvotes.size%>"
  unlikeVoteCount.innerText = "<%= @post.get_downvotes.size%>"
}
downvote()

app/views/posts/index.html.erb
<div class="container">
  <div class='page-title'>
    <h1 class='text-center logo-img-top nba-logo text-center mb-5 mt-4'><%= image_tag "nba-logo.png", alt: "NBA-logo"%> Forum</h1>
  </div>
  <div class="flex-container">
    <ul class="mt-3 nav nav-tabs" id="myTab" role="tablist">
      <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link active" id="favorite-tab" data-toggle="tab" href="#favorite" role="tab" aria-controls="favorite" aria-selected="true">Followed</a>
        </li>
      <% end %>
      <li class="nav-item">
        <a class="nav-link" id="allposts-tab" data-toggle="tab" href="#allposts" role="tab" aria-controls="allposts" aria-selected="false">all posts</a>
      </li>
      <% if user_signed_in? %>
        <li  class="nav-item">
          <a class="nav-link" id="myposts-tab" data-toggle="tab" href="#myposts", role="tab" aria-controls="myposts" aria-selected="false">my posts</a>
        </li>
      <% end %>
      <li  class="nav-item">
        <a class="nav-link" id="newpost-tab" data-toggle="tab" href="#newpost" role="tab" aria-controls="newpost" aria-selected="false" style="background-color: #91bd3a">Create</a>
      </li>
    </ul>
  </div>
  <div class="tab-content">
    <% if user_signed_in? %>
      <div class="tab-pane active" id="favorite" role="tabpanel" aria-labelledby="favorite-tab">
        <div class="posts-container">
          <div class="favorites-post-container">
            <% if @professionals_posts.size >= 1 %>
              <% @professionals_posts.each do |favorite| %>
                <div class="col-12 justify-content-center d-flex">
                  <%= link_to post_path(favorite.id) do %>
                    <div class="posts-card stretched-link card-body">
                      <div class="card-body-preview">
                        <div class="card-preview-text">
                          <h5 class="card-title"><%= favorite.title %></h5>
                          <p class="card-text"><%= favorite.content[0...150] %></p>
                        </div>
                        <% unless favorite.photo.blank?  %>
                          <%= cl_image_tag favorite.photo, width: 100, class: "post_image_preview"%>
                        <% end %>
                      </div>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="tab-pane" id="allposts" role="tabpanel" aria-labelledby="allposts-tab">
      <div class="posts-container">
        <div class="all-posts-container">
          <% @posts.each do |post| %>
            <div class="col-12 justify-content-center d-flex">
              <%= link_to post_path(post) do %>
                <div class="posts-card">
                  <div class="post-card-body card-body">
                    <div class="card-body-preview">
                      <div class="card-preview-text">
                        <h5 class="card-title"><%= post.title %></h5>
                        <p class="card-text"><%= post.content[0...150] %>...</p>
                      </div>
                      <% unless post.photo.blank?  %>
                        <%= cl_image_tag post.photo, width: 100, class: "post_image_preview" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="tab-pane" id="newpost" role="tabpanel" aria-labelledby="newpost-tab">
      <div class="posts-container">
        <div class="new-post-container">
          <% if policy(Post).create? %>
            <%= render 'shared/form' %>
          <% end %>
        </div>
      </div>
    </div>
    <% if user_signed_in? %>
      <div class="tab-pane" id="myposts" role="tabpanel" aria-labelledby="myposts-tab">
        <div class="posts-container">
          <div class="my-posts-container">
            <% @myposts.each do |post| %>
              <div class="col-12 justify-content-center d-flex">
                <%= link_to post_path(post) do %>
                  <div class="posts-card stretched-link card-body">
                    <div class="card-body-preview">
                      <div class="card-preview-text">
                        <h5 class="card-title"><%= post.title %></h5>
                        <p class="card-text"><%= post.content[0...150] %></p>
                      </div>
                      <% unless post.photo.blank?  %>
                        <%= cl_image_tag post.photo, width: 100, class: "post_image_preview"%>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<% if policy(Post).create? %>
<div class="new-post-container">
  <%= render 'shared/form' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="container post-show">
  <div class="votes">
    <%= link_to upvote_post_path(@post), method: :get, remote: true, class: 'like_post' do %>
      <button type="button" class="btn btn-info" aria-label="Left Align">
        <i class="fa fa-arrow-up"></i>
        <span class="badge vote_count"><%= @post.get_upvotes.size %></span>
      </button>
    <% end %>
    <%= link_to downvote_post_path(@post), method: :get, remote: true, class: 'unlike_post' do %>
      <button type="button" class="btn btn-info" aria-label="Left Align">
          <i class="fa fa-arrow-down"></i>
          <span class="badge vote_count"><%= @post.get_downvotes.size %></span>
      </button>
    <% end %>
  </div>
  <div class="post-container">
    <div class="post-content-container">
      <div class="post-content-text">
        <h1><%= @post.title %></h1>
        <p><%= @post.content %></p>
        <p class="comment-user"><%= time_ago_in_words(@post.created_at) + ' ago'  %></p>
      </div>
      <%= cl_image_tag @post.photo, class: "post_content_image" %>
    </div>
    <% if policy(Comment).create? %>
      <%= render 'shared/comment_form', parent: @post, comment: @comment,remote: false %>
    <% end %>
    <% @post.comments.each do |comment| %>
      <!-- nested p tags? -->
      <p>
        <div class="comment-container">
          <div class="d-flex justify-content-between">
            <p class="comment-user"><%= comment.user.email %></p>
            <p class="comment-user"><%= time_ago_in_words(comment.created_at) + ' ago'  %></p>
          </div>
          <p><%= comment.text%></p>
          <p>
            <a href="#" class="reply-link">
            <i class="fa fa-reply" aria-hidden="true"></i>
              Reply
            </a>
          </p>
          <div id="comment_replies_container_<%= comment.id%>">
            <div id="comment-replies-<%= comment.id %>">
              <% comment.comments.each do |subcomment| %>
                <!-- p tag in a p tag? -->
                <p id="commentOnComment_<%= subcomment.id %>">
                  <p class="subcomment"> <%= subcomment.text %></p>
                </p>
                <a href="#" class="reply-link">
                  <i class="fa fa-reply" aria-hidden="true"></i>
                  Reply
                </a>
                <div id="comment_replies_container_<%= subcomment.id %>">
                  <div id="comment-replies-<%= subcomment.id %>">
                    <% subcomment.comments.each do |subsubcomment| %>
                      <!-- <p> in a <p></p>? -->
                      <p id="commentOnComment_<%= subsubcomment.id %>">
                        <p class="subsubcomment"> <%= subsubcomment.text %></p>
                      </p>
                    <% end %>
                  </div>
                </div>
                <div class="reply-comment-form d-none" id="reply_form_<%= subcomment.id %>">
                  <%= render 'shared/comment_form', parent: subcomment, comment: Comment.new, remote: true %>
                </div>
              <% end %>
            </div>

            <% if policy(Comment).create? %>
              <div class="reply-comment-form d-none" id="reply_form_<%= comment.id %>">
                <%= render 'shared/comment_form', parent: comment, comment: Comment.new, remote: true %>
              </div>
            <% end %>
          </div>
        </div>
      </p>
    <% end %>
  </div>
</div>

app/views/posts/upvote.js.erb
function upVote(){

  const likePost = document.querySelector('.like_post');
  const unlikePost = document.querySelector('.unlike_post');
  const likeVoteCount = likePost.querySelector('.vote_count');
  const unlikeVoteCount = unlikePost.querySelector('.vote_count');

  likeVoteCount.innerText = "<%= @post.get_upvotes.size%>"
  unlikeVoteCount.innerText = "<%= @post.get_downvotes.size%>"
}
upVote()